a=int(input("a="))
b=int(input("b="))
print("suma=",a+b,sep='')
print("diferența1=",a-b,sep='')
print("diferneța2=",b-a,sep='')
print("câtul1=",a/b,sep='')
print("câtul2=",b/a,sep='')
print("produsul=",a*b,sep='')
print("ridicarea la putere=",a**b,sep='')
